"""Alertmanager environment variable names."""

from __future__ import annotations

ALERTMANAGER_URL_ENV = "ALERTMANAGER_URL"
ALERTMANAGER_BEARER_TOKEN_ENV = "ALERTMANAGER_BEARER_TOKEN"
ALERTMANAGER_USERNAME_ENV = "ALERTMANAGER_USERNAME"
ALERTMANAGER_PASSWORD_ENV = "ALERTMANAGER_PASSWORD"

__all__ = [
    "ALERTMANAGER_BEARER_TOKEN_ENV",
    "ALERTMANAGER_PASSWORD_ENV",
    "ALERTMANAGER_URL_ENV",
    "ALERTMANAGER_USERNAME_ENV",
]
