"""Azure SQL environment variable names and defaults."""

from __future__ import annotations

AZURE_SQL_SERVER_ENV = "AZURE_SQL_SERVER"
AZURE_SQL_DATABASE_ENV = "AZURE_SQL_DATABASE"
AZURE_SQL_PORT_ENV = "AZURE_SQL_PORT"
AZURE_SQL_USERNAME_ENV = "AZURE_SQL_USERNAME"
AZURE_SQL_PASSWORD_ENV = "AZURE_SQL_PASSWORD"
AZURE_SQL_DRIVER_ENV = "AZURE_SQL_DRIVER"
AZURE_SQL_ENCRYPT_ENV = "AZURE_SQL_ENCRYPT"

DEFAULT_AZURE_SQL_PORT = 1433
DEFAULT_AZURE_SQL_DRIVER = "ODBC Driver 18 for SQL Server"
DEFAULT_AZURE_SQL_TIMEOUT_SECONDS = 15.0
DEFAULT_AZURE_SQL_MAX_RESULTS = 50

__all__ = [
    "AZURE_SQL_DATABASE_ENV",
    "AZURE_SQL_DRIVER_ENV",
    "AZURE_SQL_ENCRYPT_ENV",
    "AZURE_SQL_PASSWORD_ENV",
    "AZURE_SQL_PORT_ENV",
    "AZURE_SQL_SERVER_ENV",
    "AZURE_SQL_USERNAME_ENV",
    "DEFAULT_AZURE_SQL_DRIVER",
    "DEFAULT_AZURE_SQL_MAX_RESULTS",
    "DEFAULT_AZURE_SQL_PORT",
    "DEFAULT_AZURE_SQL_TIMEOUT_SECONDS",
]
