"""Azure Monitor Log Analytics environment variable names and defaults."""

from __future__ import annotations

AZURE_LOG_ANALYTICS_WORKSPACE_ID_ENV = "AZURE_LOG_ANALYTICS_WORKSPACE_ID"
AZURE_LOG_ANALYTICS_TOKEN_ENV = "AZURE_LOG_ANALYTICS_TOKEN"
AZURE_LOG_ANALYTICS_ENDPOINT_ENV = "AZURE_LOG_ANALYTICS_ENDPOINT"
AZURE_TENANT_ID_ENV = "AZURE_TENANT_ID"
AZURE_SUBSCRIPTION_ID_ENV = "AZURE_SUBSCRIPTION_ID"
AZURE_MAX_RESULTS_ENV = "AZURE_MAX_RESULTS"

AZURE_LOG_ANALYTICS_DEFAULT_ENDPOINT = "https://api.loganalytics.io"
AZURE_MAX_RESULTS_DEFAULT = 100
AZURE_MAX_RESULTS_HARD_LIMIT = 200

__all__ = [
    "AZURE_LOG_ANALYTICS_DEFAULT_ENDPOINT",
    "AZURE_LOG_ANALYTICS_ENDPOINT_ENV",
    "AZURE_LOG_ANALYTICS_TOKEN_ENV",
    "AZURE_LOG_ANALYTICS_WORKSPACE_ID_ENV",
    "AZURE_MAX_RESULTS_DEFAULT",
    "AZURE_MAX_RESULTS_ENV",
    "AZURE_MAX_RESULTS_HARD_LIMIT",
    "AZURE_SUBSCRIPTION_ID_ENV",
    "AZURE_TENANT_ID_ENV",
]
