"""Better Stack environment variable names."""

from __future__ import annotations

BETTERSTACK_QUERY_ENDPOINT_ENV = "BETTERSTACK_QUERY_ENDPOINT"
BETTERSTACK_USERNAME_ENV = "BETTERSTACK_USERNAME"
BETTERSTACK_PASSWORD_ENV = "BETTERSTACK_PASSWORD"
BETTERSTACK_SOURCES_ENV = "BETTERSTACK_SOURCES"

__all__ = [
    "BETTERSTACK_PASSWORD_ENV",
    "BETTERSTACK_QUERY_ENDPOINT_ENV",
    "BETTERSTACK_SOURCES_ENV",
    "BETTERSTACK_USERNAME_ENV",
]
