"""GitHub API defaults and environment variable names."""

from __future__ import annotations

GITHUB_API_BASE_URL = "https://api.github.com"
GITHUB_MCP_MODE_ENV = "GITHUB_MCP_MODE"
GITHUB_MCP_URL_ENV = "GITHUB_MCP_URL"
GITHUB_MCP_COMMAND_ENV = "GITHUB_MCP_COMMAND"
GITHUB_MCP_ARGS_ENV = "GITHUB_MCP_ARGS"
GITHUB_MCP_AUTH_TOKEN_ENV = "GITHUB_MCP_AUTH_TOKEN"
GITHUB_MCP_TOOLSETS_ENV = "GITHUB_MCP_TOOLSETS"
# Distinct ecosystem names: GitHub Actions injects GITHUB_TOKEN; the gh CLI reads GH_TOKEN.
GITHUB_TOKEN_ENV = "GITHUB_TOKEN"
GH_TOKEN_ENV = "GH_TOKEN"
GITHUB_CLI_REQUIRED_SCOPES = frozenset({"read:org", "repo", "security_events", "workflow"})

__all__ = [
    "GH_TOKEN_ENV",
    "GITHUB_API_BASE_URL",
    "GITHUB_CLI_REQUIRED_SCOPES",
    "GITHUB_MCP_ARGS_ENV",
    "GITHUB_MCP_AUTH_TOKEN_ENV",
    "GITHUB_MCP_COMMAND_ENV",
    "GITHUB_MCP_MODE_ENV",
    "GITHUB_MCP_TOOLSETS_ENV",
    "GITHUB_MCP_URL_ENV",
    "GITHUB_TOKEN_ENV",
]
