"""Groundcover environment variable names."""

from __future__ import annotations

GROUNDCOVER_API_KEY_ENV = "GROUNDCOVER_API_KEY"
# Accepted as a fallback when GROUNDCOVER_API_KEY is unset; setup always writes
# the primary name.
GROUNDCOVER_MCP_TOKEN_ENV = "GROUNDCOVER_MCP_TOKEN"
GROUNDCOVER_MCP_URL_ENV = "GROUNDCOVER_MCP_URL"
GROUNDCOVER_TENANT_UUID_ENV = "GROUNDCOVER_TENANT_UUID"
GROUNDCOVER_BACKEND_ID_ENV = "GROUNDCOVER_BACKEND_ID"
GROUNDCOVER_TIMEZONE_ENV = "GROUNDCOVER_TIMEZONE"

__all__ = [
    "GROUNDCOVER_API_KEY_ENV",
    "GROUNDCOVER_BACKEND_ID_ENV",
    "GROUNDCOVER_MCP_TOKEN_ENV",
    "GROUNDCOVER_MCP_URL_ENV",
    "GROUNDCOVER_TENANT_UUID_ENV",
    "GROUNDCOVER_TIMEZONE_ENV",
]
