"""Kubernetes environment variable names."""

from __future__ import annotations

KUBECONFIG_PATH_ENV = "KUBECONFIG"
KUBECONFIG_CONTENT_ENV = "KUBECONFIG_CONTENT"
KUBECONFIG_CONTEXT_ENV = "KUBECONFIG_CONTEXT"
KUBECONFIG_NAMESPACE_ENV = "KUBECONFIG_NAMESPACE"

__all__ = [
    "KUBECONFIG_CONTENT_ENV",
    "KUBECONFIG_CONTEXT_ENV",
    "KUBECONFIG_NAMESPACE_ENV",
    "KUBECONFIG_PATH_ENV",
]
