"""MariaDB environment variable names."""

from __future__ import annotations

MARIADB_HOST_ENV = "MARIADB_HOST"
MARIADB_PORT_ENV = "MARIADB_PORT"
MARIADB_DATABASE_ENV = "MARIADB_DATABASE"
MARIADB_USERNAME_ENV = "MARIADB_USERNAME"
MARIADB_PASSWORD_ENV = "MARIADB_PASSWORD"
MARIADB_SSL_ENV = "MARIADB_SSL"

__all__ = [
    "MARIADB_DATABASE_ENV",
    "MARIADB_HOST_ENV",
    "MARIADB_PASSWORD_ENV",
    "MARIADB_PORT_ENV",
    "MARIADB_SSL_ENV",
    "MARIADB_USERNAME_ENV",
]
