"""MongoDB environment variable names."""

from __future__ import annotations

MONGODB_CONNECTION_STRING_ENV = "MONGODB_CONNECTION_STRING"
MONGODB_DATABASE_ENV = "MONGODB_DATABASE"
MONGODB_AUTH_SOURCE_ENV = "MONGODB_AUTH_SOURCE"
MONGODB_TLS_ENV = "MONGODB_TLS"

__all__ = [
    "MONGODB_AUTH_SOURCE_ENV",
    "MONGODB_CONNECTION_STRING_ENV",
    "MONGODB_DATABASE_ENV",
    "MONGODB_TLS_ENV",
]
