"""MongoDB Atlas environment variable names."""

from __future__ import annotations

MONGODB_ATLAS_PUBLIC_KEY_ENV = "MONGODB_ATLAS_PUBLIC_KEY"
MONGODB_ATLAS_PRIVATE_KEY_ENV = "MONGODB_ATLAS_PRIVATE_KEY"
MONGODB_ATLAS_PROJECT_ID_ENV = "MONGODB_ATLAS_PROJECT_ID"
MONGODB_ATLAS_BASE_URL_ENV = "MONGODB_ATLAS_BASE_URL"

__all__ = [
    "MONGODB_ATLAS_BASE_URL_ENV",
    "MONGODB_ATLAS_PRIVATE_KEY_ENV",
    "MONGODB_ATLAS_PROJECT_ID_ENV",
    "MONGODB_ATLAS_PUBLIC_KEY_ENV",
]
