"""MySQL environment variable names."""

from __future__ import annotations

MYSQL_HOST_ENV = "MYSQL_HOST"
MYSQL_PORT_ENV = "MYSQL_PORT"
MYSQL_DATABASE_ENV = "MYSQL_DATABASE"
MYSQL_USERNAME_ENV = "MYSQL_USERNAME"
MYSQL_PASSWORD_ENV = "MYSQL_PASSWORD"
MYSQL_SSL_MODE_ENV = "MYSQL_SSL_MODE"

__all__ = [
    "MYSQL_DATABASE_ENV",
    "MYSQL_HOST_ENV",
    "MYSQL_PASSWORD_ENV",
    "MYSQL_PORT_ENV",
    "MYSQL_SSL_MODE_ENV",
    "MYSQL_USERNAME_ENV",
]
