"""OpenSearch environment variable names."""

from __future__ import annotations

OPENSEARCH_URL_ENV = "OPENSEARCH_URL"
OPENSEARCH_API_KEY_ENV = "OPENSEARCH_API_KEY"
OPENSEARCH_USERNAME_ENV = "OPENSEARCH_USERNAME"
OPENSEARCH_PASSWORD_ENV = "OPENSEARCH_PASSWORD"

__all__ = [
    "OPENSEARCH_API_KEY_ENV",
    "OPENSEARCH_PASSWORD_ENV",
    "OPENSEARCH_URL_ENV",
    "OPENSEARCH_USERNAME_ENV",
]
