"""Constants for the local operations log."""

from __future__ import annotations

OPENSRE_OPERATIONS_LOG_DISABLED_ENV = "OPENSRE_OPERATIONS_LOG_DISABLED"
OPENSRE_OPERATIONS_LOG_FILENAME = "operations_log.jsonl"
DEFAULT_OPENSRE_OPERATIONS_LOG_MAX_BYTES = 5 * 1024 * 1024
OPENSRE_OPERATIONS_LOG_MAX_BYTES_ENV = "OPENSRE_OPERATIONS_LOG_MAX_BYTES"
OPENSRE_OPERATIONS_LOG_PATH_ENV = "OPENSRE_OPERATIONS_LOG_PATH"

__all__ = [
    "DEFAULT_OPENSRE_OPERATIONS_LOG_MAX_BYTES",
    "OPENSRE_OPERATIONS_LOG_DISABLED_ENV",
    "OPENSRE_OPERATIONS_LOG_FILENAME",
    "OPENSRE_OPERATIONS_LOG_MAX_BYTES_ENV",
    "OPENSRE_OPERATIONS_LOG_PATH_ENV",
]
