"""PostgreSQL environment variable names."""

from __future__ import annotations

POSTGRESQL_HOST_ENV = "POSTGRESQL_HOST"
POSTGRESQL_PORT_ENV = "POSTGRESQL_PORT"
POSTGRESQL_DATABASE_ENV = "POSTGRESQL_DATABASE"
POSTGRESQL_USERNAME_ENV = "POSTGRESQL_USERNAME"
POSTGRESQL_PASSWORD_ENV = "POSTGRESQL_PASSWORD"
POSTGRESQL_SSL_MODE_ENV = "POSTGRESQL_SSL_MODE"

__all__ = [
    "POSTGRESQL_DATABASE_ENV",
    "POSTGRESQL_HOST_ENV",
    "POSTGRESQL_PASSWORD_ENV",
    "POSTGRESQL_PORT_ENV",
    "POSTGRESQL_SSL_MODE_ENV",
    "POSTGRESQL_USERNAME_ENV",
]
