"""Railway environment variable names."""

from __future__ import annotations

RAILWAY_TOKEN_ENV = "RAILWAY_TOKEN"
RAILWAY_PROJECT_ENV = "RAILWAY_PROJECT"
RAILWAY_SERVICE_ENV = "RAILWAY_SERVICE"
RAILWAY_ENVIRONMENT_ENV = "RAILWAY_ENVIRONMENT"
RAILWAY_PATH_ENV = "RAILWAY_PATH"

__all__ = [
    "RAILWAY_ENVIRONMENT_ENV",
    "RAILWAY_PATH_ENV",
    "RAILWAY_PROJECT_ENV",
    "RAILWAY_SERVICE_ENV",
    "RAILWAY_TOKEN_ENV",
]
