"""Redis environment variable names."""

from __future__ import annotations

REDIS_HOST_ENV = "REDIS_HOST"
REDIS_PORT_ENV = "REDIS_PORT"
REDIS_USERNAME_ENV = "REDIS_USERNAME"
REDIS_PASSWORD_ENV = "REDIS_PASSWORD"
REDIS_DATABASE_ENV = "REDIS_DATABASE"
REDIS_SSL_ENV = "REDIS_SSL"

__all__ = [
    "REDIS_DATABASE_ENV",
    "REDIS_HOST_ENV",
    "REDIS_PASSWORD_ENV",
    "REDIS_PORT_ENV",
    "REDIS_SSL_ENV",
    "REDIS_USERNAME_ENV",
]
