"""ServiceNow environment variable names."""

from __future__ import annotations

SERVICENOW_INSTANCE_URL_ENV = "SERVICENOW_INSTANCE_URL"
SERVICENOW_USERNAME_ENV = "SERVICENOW_USERNAME"
SERVICENOW_PASSWORD_ENV = "SERVICENOW_PASSWORD"

__all__ = [
    "SERVICENOW_INSTANCE_URL_ENV",
    "SERVICENOW_PASSWORD_ENV",
    "SERVICENOW_USERNAME_ENV",
]
