"""SMTP environment variable names."""

from __future__ import annotations

SMTP_HOST_ENV = "SMTP_HOST"
SMTP_PORT_ENV = "SMTP_PORT"
SMTP_SECURITY_ENV = "SMTP_SECURITY"
SMTP_USERNAME_ENV = "SMTP_USERNAME"
SMTP_PASSWORD_ENV = "SMTP_PASSWORD"
SMTP_FROM_ADDRESS_ENV = "SMTP_FROM_ADDRESS"
SMTP_DEFAULT_TO_ENV = "SMTP_DEFAULT_TO"

__all__ = [
    "SMTP_DEFAULT_TO_ENV",
    "SMTP_FROM_ADDRESS_ENV",
    "SMTP_HOST_ENV",
    "SMTP_PASSWORD_ENV",
    "SMTP_PORT_ENV",
    "SMTP_SECURITY_ENV",
    "SMTP_USERNAME_ENV",
]
