from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import StrEnum

from core.incident import Incident, IncidentStatus


class DecisionTraceEventType(StrEnum):
    """Chronological event in the incident decision log."""

    INCIDENT_DETECTED = "incident_detected"
    TRIAGED = "triaged"
    INCIDENT_TRIAGED = "incident_triaged"
    EVIDENCE_COLLECTED = "evidence_collected"
    INVESTIGATION_STARTED = "investigation_started"
    HYPOTHESIS_CREATED = "hypothesis_created"
    HYPOTHESIS_TESTED = "hypothesis_tested"
    ROOT_CAUSE_IDENTIFIED = "root_cause_identified"
    RISK_ASSESSED = "risk_assessed"
    APPROVAL_REQUESTED = "approval_requested"
    APPROVED = "approved"
    REJECTED = "rejected"
    REMEDIATION_PROPOSED = "remediation_proposed"
    REMEDIATION_STARTED = "remediation_started"
    REMEDIATION_COMPLETED = "remediation_completed"
    REMEDIATION_FAILED = "remediation_failed"
    RECOVERY_VERIFIED = "recovery_verified"
    RECOVERY_FAILED = "recovery_failed"
    RESOLVED = "resolved"


@dataclass
class DecisionTraceEvent:
    """One decision/observation in the incident history."""

    event_type: DecisionTraceEventType | str
    summary: str
    actor: str
    incident_id: str | None = None
    action_id: str | None = None
    execution_id: str | None = None
    evidence_ids: list[str] = field(default_factory=list)
    timestamp: str = field(default_factory=lambda: datetime.now(UTC).isoformat())

    def __post_init__(self) -> None:
        if isinstance(self.event_type, str):
            self.event_type = DecisionTraceEventType(self.event_type)

    def to_dict(self) -> dict[str, object]:
        return {
            "event_type": self.event_type.value,
            "summary": self.summary,
            "actor": self.actor,
            "incident_id": self.incident_id,
            "action_id": self.action_id,
            "execution_id": self.execution_id,
            "evidence_ids": self.evidence_ids,
            "timestamp": self.timestamp,
        }


@dataclass
class DecisionTrace:
    """A chronological trace of decisions and state changes for an incident."""

    incident_id: str
    events: list[DecisionTraceEvent] = field(default_factory=list)

    def append_event(
        self,
        event_type: DecisionTraceEventType | str,
        summary: str,
        actor: str,
        *,
        incident_id: str | None = None,
        action_id: str | None = None,
        execution_id: str | None = None,
        evidence_ids: list[str] | None = None,
    ) -> DecisionTraceEvent:
        event = DecisionTraceEvent(
            event_type=event_type,
            summary=summary,
            actor=actor,
            incident_id=incident_id or self.incident_id,
            action_id=action_id,
            execution_id=execution_id,
            evidence_ids=list(evidence_ids or []),
        )
        self.events.append(event)
        return event

    def replay(self, incident: Incident) -> "ReplayResult":
        current_state = incident.status
        for event in self.events:
            if event.event_type is DecisionTraceEventType.ROOT_CAUSE_IDENTIFIED:
                current_state = IncidentStatus.ROOT_CAUSE_IDENTIFIED
            elif event.event_type is DecisionTraceEventType.RESOLVED:
                current_state = IncidentStatus.RESOLVED
            elif event.event_type is DecisionTraceEventType.RECOVERY_VERIFIED:
                # The verification event documents recovery, but it does not itself
                # advance the incident lifecycle beyond the last explicit state change.
                continue
        return ReplayResult(
            incident_id=self.incident_id,
            current_state=current_state,
            decision_history=self.events,
        )


@dataclass
class ReplayResult:
    """Result generated by replaying a decision trace against a current incident."""

    incident_id: str
    current_state: IncidentStatus
    decision_history: list[DecisionTraceEvent]


@dataclass
class Postmortem:
    """After-action review and lessons learned."""

    incident_summary: str
    customer_or_system_impact: str
    timeline: list[str]
    root_cause: str
    supporting_evidence: list[str]
    remediation: str
    recovery_verification: str
    human_intervention: str
    lessons_learned: list[str]

    def to_dict(self) -> dict[str, object]:
        return {
            "incident_summary": self.incident_summary,
            "customer_or_system_impact": self.customer_or_system_impact,
            "timeline": self.timeline,
            "root_cause": self.root_cause,
            "supporting_evidence": self.supporting_evidence,
            "remediation": self.remediation,
            "recovery_verification": self.recovery_verification,
            "human_intervention": self.human_intervention,
            "lessons_learned": self.lessons_learned,
        }


__all__ = [
    "DecisionTrace",
    "DecisionTraceEvent",
    "DecisionTraceEventType",
    "Postmortem",
    "ReplayResult",
]
